name: Lint

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  superlinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run super linter
        uses: docker://github/super-linter:v2.2.0
